import '@/styles/globals.css';
import '@/styles/theme.css';
import 'sweetalert2/dist/sweetalert2.min.css';
import '@xyflow/react/dist/style.css';
import type { Metadata } from 'next';
import themeConfig from '../../theme.config';
import { QueryProvider } from './provider/query.provider';
import { GlobalProvider } from './provider/global.provider';
import GlobalModals from './provider/GlobalModals';
import { SocketProvider } from './provider/socketContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <GlobalProvider>
        <QueryProvider>
        <SocketProvider>
          <GlobalModals />
            <div className={`${themeConfig.navbar} `}>{children}</div>
          </SocketProvider>
        </QueryProvider>
      </GlobalProvider>
    </html>
  );
}
