import Header from "@/components/layout/header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "./provider/query.provider";
import { ThemeProvider } from "./provider/theme.provider";
import themeConfig from "../../theme.config";
import Setting from "@/components/layout/setting";
import ContentAnimation from "@/components/layout/content-animation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <QueryProvider>
          <ThemeProvider>
          <div className="relative">
            <Setting/>
        
        <div className={`${themeConfig.navbar}`}>
          <Header />
          <ContentAnimation>
          {children}
          </ContentAnimation>
        </div>

        </div>
        </ThemeProvider>
        </QueryProvider>
        
      </body>
    </html>
  );
}
